require('settings')
require('keymappings')
require('colorscheme')
require('globals')

require('plugins')
require('comment-lua')
require('telescope-lua')
require('completion-lua')
require('lspinstall-lua')
require('lspsaga-lua')
require('lsp_signature-lua')
require('treesitter-lua')
require('gitsigns-lua')
require('autopairs-lua')
require('rainbow_parentheses-lua')
require('lir-lua')
require('devicons-lua')

require('lsp')
